######################################
## Minio Server Service
######################################
apiVersion: v1
kind: Service
metadata:
  name: minio-server-svc
  namespace: airflow
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: minio
  ports:
    - name: minio-port
      protocol: TCP
      port: 9000
      targetPort: minio-port
---
######################################
## Minio UI Service
######################################
apiVersion: v1
kind: Service
metadata:
  name: minio-console-svc
  namespace: airflow
spec:
  type: ClusterIP
  selector:
    component: minio
  ports:
    - name: minio-console
      protocol: TCP
      port: 9001
      targetPort: minio-console
---
######################################
## Minio StatefulSet
######################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-deployment
  namespace: airflow
spec:
  serviceName: minio-server-svc
  replicas: 1
  selector:
    matchLabels:
      component: minio
  template:
    metadata:
      labels:
        component: minio
    spec:
      serviceAccountName: airflow-sa
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          resources: {}
            # requests:
            #   cpu: "125m"
            #   memory: "128Mi"
            #   ephemeral-storage: "200Mi"
            # limits:
            #   cpu: "250m"
            #   memory: "256Mi"
            #   ephemeral-storage: "500Mi"
          args: ["server", "/data", "--console-address", ":9001"]
          volumeMounts:
            - name: minio-data
              mountPath: /data
          ports:
            - containerPort: 9000
              name: minio-port
            - containerPort: 9001
              name: minio-console
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: MINIO_ROOT_PASSWORD
          # livenessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - "--fail"
          #       - http://localhost:9000/minio/health/ready
          #   initialDelaySeconds: 30
          #   failureThreshold: 3
          #   periodSeconds: 10
          # readinessProbe:
          #   exec:
          #     command:
          #       - curl
          #       - "--fail"
          #       - http://localhost:9000/minio/health/ready
          #   initialDelaySeconds: 30
          #   failureThreshold: 3
          #   periodSeconds: 10
          # startupProbe:
          #   exec:
          #     command:
          #       - curl
          #       - "--fail"
          #       - http://localhost:9000/minio/health/ready
          #   initialDelaySeconds: 30
          #   failureThreshold: 3
          #   periodSeconds: 10

  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minio-data
      spec:
        volumeName: minio-pv
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
