######################################
## Redis Service
######################################
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: airflow
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: redis
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: redis-port
---
######################################
## Redis Statefulset
######################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-deployment
  namespace: airflow
spec:
  serviceName: redis-svc
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      serviceAccountName: airflow-sa
      securityContext:
        runAsUser: 0
      containers:
        - name: redis
          image: redis:7.2-bookworm
          imagePullPolicy: IfNotPresent
          resources: {}
            # requests:
            #   cpu: "125m"
            #   memory: "128Mi"
            #   ephemeral-storage: "200Mi"
            # limits:
            #   cpu: "250m"
            #   memory: "256Mi"
            #   ephemeral-storage: "500Mi"
          ports:
            - name: redis-port
              containerPort: 6379
          command: ["/bin/sh", "-c", "redis-server --requirepass ${REDIS_PASSWORD}"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: REDIS_PASSWORD
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command: ["redis-cli", "ping"]
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        volumeName: redis-pv
        storageClassName: ""
        resources:
          requests:
            storage: "500Mi"
