services:
  scheduler:
    networks:
      - shared-network

  triggerer:
    networks:
      - shared-network

  api-server:
    networks:
      - shared-network

  dag-processor:
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
    external: true
