######################################
## Airflow Run Migration Job
######################################
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-add-connection
  namespace: airflow
  labels:
    tier: airflow
    component: add-connection-job
    release: airflow
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        tier: airflow
        component: run-migrations-job
    spec:
      securityContext:
        runAsUser: 50000
        fsGroup: 0
      restartPolicy: OnFailure
      serviceAccountName: airflow-sa
      containers:
        - name: add-connection
          image: iadebisi/airflow-spark
          imagePullPolicy: IfNotPresent
          args:
            - bash
            - -c
            - |
              exec airflow connections add "${SPARK_CONN_NAME}" \
              --conn-type "spark" \
              --conn-host "${SPARK_CONN_HOST}" \
              --conn-port "${SPARK_CONN_PORT}"
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secrets
          resources: {}
          volumeMounts:
            - name: airflow-data
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: config/airflow.cfg
              readOnly: true
      volumes:
        - name: airflow-data
          persistentVolumeClaim:
            claimName: airflow-pvc
